# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Elims.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sqlite3

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog2(object):
    def __init__(self):
        self.bwinner = ""
        self.arunnerup = ""
        self.awinner = ""
        self.eplayers = []

    def getplayers(self):
        conn = sqlite3.connect("bptournament.db")
        c = conn.cursor()
        print("moi")
        query = c.execute("SELECT * FROM advancers")
        players = c.fetchall()
        for player in players:
            p, = player
            self.eplayers.append(p)
        print("toimi?", self.eplayers)
        return self.eplayers

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1104, 880)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(120, 120, 211, 73))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.eplayers = self.getplayers()
        print("häh", self.eplayers)
        print("aaaa", self.awinner)
        self.bwinner = self.eplayers[2]
        self.arunnerup = self.eplayers[1]
        self.awinner = self.eplayers[0]
        self.brunnerup = self.eplayers[3]
        self.cwinner = self.eplayers[4]
        self.crunnerup = self.eplayers[5]
        self.thirdone = self.eplayers[6]
        self.thirdtwo = self.eplayers[7]
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName(self.awinner)
        self.pushButton.clicked.connect(self.getwinner1)
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName(self.thirdone)
        self.pushButton_2.clicked.connect(self.getwinner2)
        self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(120, 250, 211, 71))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_3.setObjectName(self.bwinner)
        self.pushButton_3.clicked.connect(self.getwinner3)
        self.gridLayout_3.addWidget(self.pushButton_3, 0, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_4.setObjectName(self.thirdtwo)
        self.pushButton_4.clicked.connect(self.getwinner4)
        self.gridLayout_3.addWidget(self.pushButton_4, 1, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(120, 370, 211, 71))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_5.setObjectName(self.cwinner)
        self.pushButton_5.clicked.connect(self.getwinner5)
        self.gridLayout_4.addWidget(self.pushButton_5, 0, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_6.setObjectName(self.arunnerup)
        self.pushButton_6.clicked.connect(self.getwinner6)
        self.gridLayout_4.addWidget(self.pushButton_6, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(130, 50, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(420, 170, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(730, 230, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(120, 490, 211, 71))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_7.setObjectName(self.brunnerup)
        self.pushButton_7.clicked.connect(self.getwinner7)
        self.gridLayout_5.addWidget(self.pushButton_7, 0, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_8.setObjectName(self.crunnerup)
        self.pushButton_8.clicked.connect(self.getwinner8)
        self.gridLayout_5.addWidget(self.pushButton_8, 1, 0, 1, 1)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(380, 360, 211, 71))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_9.clicked.connect(self.semiwinner3)
        self.gridLayout_6.addWidget(self.pushButton_9, 0, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.clicked.connect(self.semiwinner4)
        self.gridLayout_6.addWidget(self.pushButton_10, 1, 0, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(380, 260, 211, 71))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pushButton_11 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_11.clicked.connect(self.semiwinner1)
        self.gridLayout_7.addWidget(self.pushButton_11, 0, 0, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_12.clicked.connect(self.semiwinner2)
        self.gridLayout_7.addWidget(self.pushButton_12, 1, 0, 1, 1)
        self.gridLayoutWidget_7 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(660, 300, 211, 71))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButton_13 = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_13.clicked.connect(self.finale1)
        self.gridLayout_8.addWidget(self.pushButton_13, 0, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_14.clicked.connect(self.finale2)
        self.gridLayout_8.addWidget(self.pushButton_14, 1, 0, 1, 1)

        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_6.setGeometry(QtCore.QRect(600, 600, 231, 71))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", self.awinner))
        self.pushButton_2.setText(_translate("Dialog", self.thirdone))
        self.pushButton_3.setText(_translate("Dialog", self.bwinner))
        self.pushButton_4.setText(_translate("Dialog", self.thirdtwo))
        self.pushButton_5.setText(_translate("Dialog", self.cwinner))
        self.pushButton_6.setText(_translate("Dialog", self.arunnerup))
        self.label_3.setText(_translate("Dialog", "Quartefinals"))
        self.label_4.setText(_translate("Dialog", "Semifinals"))
        self.label_17.setText(_translate("Dialog", "Finale"))
        self.label_6.setText(_translate("Dialog", "Winner"))
        self.pushButton_7.setText(_translate("Dialog", self.brunnerup))
        self.pushButton_8.setText(_translate("Dialog", self.crunnerup))
        self.pushButton_9.setText(_translate("Dialog", "Semi3"))
        self.pushButton_10.setText(_translate("Dialog", "Semi4"))
        self.pushButton_11.setText(_translate("Dialog", "Semi1"))
        self.pushButton_12.setText(_translate("Dialog", "Semi2"))
        self.pushButton_13.setText(_translate("Dialog", "Final1"))
        self.pushButton_14.setText(_translate("Dialog", "Final2"))

    def getwinner1(self):
        self.pushButton_11.setText(self.awinner)
        self.pushButton_11.setObjectName(self.awinner)

    def getwinner2(self):
        self.pushButton_11.setText(self.thirdone)
        self.pushButton_11.setObjectName(self.thirdone)
    def getwinner3(self):
        self.pushButton_12.setText(self.bwinner)
        self.pushButton_12.setObjectName(self.bwinner)

    def getwinner4(self):
        self.pushButton_12.setText(self.thirdtwo)
        self.pushButton_12.setObjectName(self.thirdtwo)
    def getwinner5(self):
        self.pushButton_9.setText(self.cwinner)
        self.pushButton_9.setObjectName(self.cwinner)
    def getwinner6(self):
        self.pushButton_9.setText(self.arunnerup)
        self.pushButton_9.setObjectName(self.arunnerup)
    def getwinner7(self):
        self.pushButton_10.setText(self.brunnerup)
        self.pushButton_10.setObjectName(self.brunnerup)
    def getwinner8(self):
        self.pushButton_10.setText(self.crunnerup)
        self.pushButton_10.setObjectName(self.crunnerup)

    def semiwinner1(self):
        self.sem1 = self.pushButton_11.objectName()
        self.pushButton_13.setText(self.sem1)
        self.pushButton_13.setObjectName(self.sem1)
        
    def semiwinner2(self):
        self.sem2 = self.pushButton_12.objectName()
        self.pushButton_13.setText(self.sem2)
        self.pushButton_13.setObjectName(self.sem2)

    def semiwinner3(self):
        self.sem3 = self.pushButton_9.objectName()
        self.pushButton_14.setText(self.sem3)
        self.pushButton_14.setObjectName(self.sem3)

    def semiwinner4(self):
        self.sem4 = self.pushButton_10.objectName()
        self.pushButton_14.setText(self.sem4)
        self.pushButton_14.setObjectName(self.sem4)

    def finale1(self):
        self.fin = self.pushButton_13.objectName()
        font = QtGui.QFont()
        font.setPointSize(35)
        self.label_6.setText(self.fin)
        print("loppu")
    def finale2(self):
        self.fin = self.pushButton_14.objectName()
        font = QtGui.QFont()
        font.setPointSize(35)
        self.label_6.setText(self.fin)
        print("loppu")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog2()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
